stages:
  download_data:
    cmd: python src/data/download_data.py
    deps:
      - src/data/download_data.py
      - config/data_config.yaml
    outs:
      - data/raw/yellow_tripdata_2025-01.parquet  # FIXED: Changed to 2025
      - data/raw/yellow_tripdata_2025-02.parquet  
      - data/raw/yellow_tripdata_2025-03.parquet
      - data/raw/taxi_zone_lookup.csv

  preprocess_data:
    cmd: python src/models/train_model.py --config config/model_config.yaml  # Use fixed script
    deps:
      - src/data/preprocess.py
      - config/data_config.yaml
      - data/raw/yellow_tripdata_2025-01.parquet  # FIXED: 2025 data
      - data/raw/yellow_tripdata_2025-02.parquet
      - data/raw/yellow_tripdata_2025-03.parquet
      - data/raw/taxi_zone_lookup.csv
    outs:
      - data/processed/cleaned_trips.parquet
    metrics:
      - metrics/data_quality.json

  feature_engineering:
    cmd: python src/data/feature_engineering.py --config config/data_config.yaml
    deps:
      - src/data/feature_engineering.py
      - config/data_config.yaml
      - data/processed/cleaned_trips.parquet
    outs:
      - data/processed/aggregated_h3_features.parquet
      - data/processed/weather_data.parquet
    metrics:
      - metrics/feature_stats.json

  train_model:
    cmd: python src/models/train_model.py --config config/model_config.yaml  # Use fixed script
    deps:
      - src/models/train_model.py
      - config/model_config.yaml
      - data/processed/aggregated_h3_features.parquet
      - data/processed/weather_data.parquet
    outs:
      - models/xgboost_model.pkl
      - models/model_metadata.json
    metrics:
      - metrics/model_performance.json
    plots:
      - plots/feature_importance.json