model:
  type: "xgboost"
  features:
    - ema3
    - trip_prev
    - demand_trend
    - hour
    - weekday
    - temperature_f
    - is_raining
    - is_cold
    - is_weekend
    - avg_dist
    - avg_fare
    - is_rush_hour
  parameters:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    random_state: 42
    n_jobs: -1
    subsample: 0.8
    colsample_bytree: 0.8

training:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  stratify: false

hyperparameter_tuning:
  enabled: false
  method: "random_search"
  n_iter: 50
  cv_folds: 5
  param_distributions:
    n_estimators: [50, 100, 200, 300]
    max_depth: [3, 4, 5, 6, 7, 8]
    learning_rate: [0.01, 0.05, 0.1, 0.15, 0.2]
    subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
    colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]

metrics:
  primary: "mae"
  track:
    - mae
    - rmse
    - mape
    - r2_score

model_selection:
  criteria: "mae"
  direction: "minimize"

mlflow:
  experiment_name: "taxi-demand-prediction"
  run_name_prefix: "xgboost-v"
  tracking_uri: "file:./mlruns"
  log_artifacts: true
  log_model: true